# -------------------------------------------------------
#
#        |
#       / \
#      / _ \                  ESA - PROJECT
#     |.o '.|
#     |'._.'|          BLACK SEA DEOXYGENATION EMULATOR
#     |     |
#   ,'|  |  |`.             BY VICTOR MANGELEER
#  /  |  |  |  \
#  |,-'--|--'-.|                2023-2024
#
#
# -------------------------------------------------------
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#

config:

  # WandB
  "Project"             : ["ESA - Cluster (Diffusion)"]
  "Mode"                : ["online"]

  # Data
  "Window (Inputs)"     : [1, 7, 14, 30, 60, 120]
  "Window (Outputs)"    : [10]
  "Frequencies"         : [256]
  "Scaling"             : [4]

  # Model & Training
  "Architecture"        : ["UNET"]
  "Number of Gaussians" : [2, 5, 10]
  "Epochs"              : [10]
  "Batch Size"          : [32]
  "Learning Rate"       : [0.0005]
  "Number of Workers"   : [2]

cluster:
  "Dawgz"    : True
  "CPUS"     : 2
  "GPUS"     : 4
  "RAM"      : "240GB"
  "TIME"     : "48:00:00"
  "PARTITION": "ia"