# -------------------------------------------------------
#
#        |
#       / \
#      / _ \                  ESA - PROJECT
#     |.o '.|
#     |'._.'|          BLACK SEA DEOXYGENATION EMULATOR
#     |     |
#   ,'|  |  |`.             BY VICTOR MANGELEER
#  /  |  |  |  \
#  |,-'--|--'-.|                2023-2024
#
#
# -------------------------------------------------------
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#

config:

  # WandB
  "Project"           : ["ESA - Cluster"]
  "Mode"              : ["online"]

  # Data
  "Window (Inputs)"   : [1, 3, 7, 14, 30, 60, 120, 150, 180]
  "Window (Outputs)"  : [10]
  "Frequencies"       : [64, 128]
  "Scaling"           : [1, 3, 5]

  # Model & Training
  "Architecture"      : ["UNET"]
  "Epochs"            : [20]
  "Batch Size"        : [16]
  "Learning Rate"     : [0.0001]
  "Number of Workers" : [1]

cluster:
  "Dawgz"    : True
  "CPUS"     : 2
  "GPUS"     : 4
  "RAM"      : "240GB"
  "TIME"     : "12:00:00"
  "PARTITION": "ia"


# Notes:
# - Scaling    : 5 (max) -> 121M parameters
# - Batch Size : 16 (on 4 GPUs) if you go far in the past (120 >) otherwise 32 works
# - LR         : 0.0001 seems to be the most appropriate
# - Workers    : 1 (for now)