# -------------------------------------------------------
#
#        |
#       / \
#      / _ \                  ESA - PROJECT
#     |.o '.|
#     |'._.'|          BLACK SEA DEOXYGENATION EMULATOR
#     |     |
#   ,'|  |  |`.             BY VICTOR MANGELEER
#  /  |  |  |  \
#  |,-'--|--'-.|                2023-2024
#
#
# -------------------------------------------------------
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#
config:

  # WandB
  "Project"                 : ["Experiments-ESA"]

  # Data
  "Month (Starting)"        : [1]
  "Month (Ending)"          : [12]
  "Year (Starting)"         : [1980]
  "Year (Ending)"           : [2010]
  "Problem"                 : ["regression"]
  "Hypoxia Treshold"        : [63]
  "Depth"                   : [200]
  "Inputs"                  : [["temperature", "salinity", "chlorophyll", "kshort", "klong"]]
  "Window (Inputs)"         : [30, 60, 90, 120, 150, 180, 210, 240, 270, 330, 360]
  "Window (Output)"         : [1]
  "Window (Transformation)" : [15, 30]

  # Model & Training
  "Architecture"            : ["UNET"]
  "Scaling"                 : [8]
  "Kernel Size"             : [3]
  "Datasets Size"           : [[0.6, 0.3]]
  "Loss Weights"            : [[1, 1]]
  "Learning Rate"           : [0.001]
  "Batch Size"              : [16]
  "Epochs"                  : [20]

cluster:
  "Dawgz"    : True
  "CPUS"     : 1
  "GPUS"     : 1
  "RAM"      : "1512GB"
  "TIME"     : "03:00:00"
  "PARTITION": "ia"