# -------------------------------------------------------
#
#        |
#       / \
#      / _ \                  ESA - PROJECT
#     |.o '.|
#     |'._.'|          BLACK SEA DEOXYGENATION EMULATOR
#     |     |
#   ,'|  |  |`.             BY VICTOR MANGELEER
#  /  |  |  |  \
#  |,-'--|--'-.|                2023-2024
#
#
# -------------------------------------------------------
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#
config:

  # WandB
  "Project"           : "ESA - Local"
  "Mode"              : "online"

  # Data
  "Window (Inputs)"   : 1
  "Window (Outputs)"  : 10
  "Frequencies"       : 16
  "Scaling"           : 1

  # Model & Training
  "Architecture"      : "UNET"
  "Epochs"            : 20
  "Batch Size"        : 8
  "Learning Rate"     : 0.0001
  "Number of Workers" : 2

cluster:
  "Dawgz"    : False
  "CPUS"     : 2
  "GPUS"     : 1
  "RAM"      : "120GB"
  "TIME"     : "06:00:00"
  "PARTITION": "ia"